import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

// Toast
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("")}>
        <ToastContainer position="top-center" />
        {children}
      </body>
    </html>
  );
}
