import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { UserProvider } from "@/contexts/user";
import { ToastProvider } from "@/contexts/toast";
import { LearningProvider } from "@/contexts/learning";
import ToastMessage from "@/components/application/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("")}>
        <UserProvider>
          <LearningProvider>
            <ToastProvider>
              <ToastMessage />
              {children}
            </ToastProvider>
          </LearningProvider>
        </UserProvider>
      </body>
    </html>
  );
}
